RA-18-implement-favorites-screen
M-Vadim-dev/MyApp pull request #17
Opened 2024-10-16 20:39 UTC by M-Vadim-dev

2024-10-17 10:38 UTC, Churickoid requested changes

2024-10-17 10:38 UTC, Churickoid commented on app/src/main/res/layout/fragment_favorites.xml
> +        android:contentDescription="@string/text_favorites"
contentDescription нету смысла прописывать для текста, он как раз и произносит то, что содержится в textView

2024-10-17 10:38 UTC, Churickoid commented on app/src/main/res/layout/fragment_favorites.xml
> +        app:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
Давай заменем на более простой LinearLayoutManager и уберем spanCount.
GridLayoutManager нужен только в случаях, когда нужно построить сетку как на экранах категории, в остальных местах нам достаточно LinearLayoutManager

2024-10-17 10:38 UTC, Churickoid commented on app/src/main/res/layout/fragment_favorites.xml
> +        android:contentDescription="@string/button_favourites"
Давай переименуем строку в text_favorites, а то сбивает немного нейминг

2024-10-18 16:23 UTC, ievetrovdev approved these changes

2024-10-19 17:38 UTC, merged