RA-03-layout-navigation-buttons
M-Vadim-dev/MyApp pull request #2
Opened 2024-08-30 23:50 UTC by M-Vadim-dev

2024-08-30 23:50 UTC, M-Vadim-dev commented
не уверен, что всё правильно сделал)

2024-08-31 20:11 UTC, ievetrovdev requested changes

2024-08-31 20:11 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:backgroundTint="#525DC0"
Все значения не забываем выносить в ресурсы и переиспользовать. Размеры элементов/шрифтов, цвета, строки

Про ресурсы цветов: следует выбрать **некий определенный стиль названия айдишников**. Можно делать название в стиле назначения или использовать названия цветов. Но самое основное – рекомендую ко всем цветам добавлять `color` в конце. Чтобы если что можно было легко искать применение этого цвета по всему проекту.

2024-08-31 20:11 UTC, ievetrovdev commented on app/src/main/java/com/example/myapp/MainActivity.kt
> +        binding.btnCategory.text = "Категории"
Когда ты вызываешь setContentView(binding.root), ты прикрепляешь к Activity свою xml разметку. Сейчас ты дублируешь дважды установку текста для кнопки, первый раз текст установился в разметке xml.  Так делать не надо.
Здесь прописывай только значения, которые меняются динамически

2024-08-31 20:11 UTC, ievetrovdev commented on app/src/main/java/com/example/myapp/MainActivity.kt
> +        binding.btnCategory.setTextColor(Color.WHITE)
тоже самое с цветом

2024-08-31 20:11 UTC, ievetrovdev commented on app/src/main/java/com/example/myapp/MainActivity.kt
> +        binding.btnCategory.isVisible = true
по стандарту у всех view isVisible = true, указывать повторно - лишнее

2024-08-31 20:11 UTC, ievetrovdev commented on app/src/main/res/drawable/shape_rounded_button.xml
> +    <corners android:radius="8dp" />
На этом этапе Shape Drawable нам не понадобится. Скругленные углы кнопки задаются через стиль. Например, `<item name="cornerRadius">@dimen/main_space_half_8</item>`
Этот параметр ты уже добавил

2024-08-31 20:11 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="@dimen/padding_button"
Не обязательно для каждой стороны прописывать марджины по отдельности. Есть более универсальные атрибуты.
android:layout_margin=""
android:layout_marginHorizontal=""
android:layout_marginVertical=""

2024-08-31 20:11 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="padding_button">16dp</dimen>
в Android есть отдельный параметр padding, может возникнуть путаница, что  используется эти параметры для него.
Как правило в макетах есть самые популярные размеры, это один из них, он будет использоваться не только для кнопок.
Можно в названии писать цифру в конце, которая означает размер.
Так вот этот размер можно назвать main_space_16. А половину от него, например, так main_space_half_8. Это будет красиво и единообразно.

2024-08-31 20:11 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="day_status_bar_color">#F4FAFF</color>
Повторять значения одних и тех же цветов с разными айдишниками не рекомендуется. Пусть в ресурсах хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-08-31 20:11 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_marginEnd="4dp"
вынести в ресурсы

2024-08-31 20:11 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:backgroundTint="#E13E3E"
вынести в ресурсы

2024-08-31 20:11 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +    android:fitsSystemWindows="true"
молодец, что добавил такой параметр

2024-08-31 20:11 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="app_name" translatable="false">MyApp</string>
Технически название приложения для рецептов RecipeApp) Не так критично, но все таки будет более релевантно.

2024-08-31 20:11 UTC, ievetrovdev commented on app/src/main/res/values-eng/strings.xml
> +    <string name="app_name">MyApp</string>
за добавление английской локализации отдельный лайк

2024-08-31 20:11 UTC, ievetrovdev commented on app/src/main/java/com/example/myapp/MainActivity.kt
> +//        enableEdgeToEdge()
закомиченную логику лучше не вливать в main ветку

2024-08-31 20:11 UTC, ievetrovdev commented on app/src/main/java/com/example/myapp/MainActivity.kt
> +//        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main)) { v, insets ->
закомиченную логику лучше не вливать в main ветку

2024-09-01 18:43 UTC, ievetrovdev requested changes

2024-09-01 18:43 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +    <style name="StyleNavButton2" parent="StyleNavButton">
смотри, стиль мы создаем, чтоб не прописывать одинаковые параметры для нескольких элементов. Пока закономерность такая, что цвета у всех кнопок разные, это в стиль выносить не надо. Пропеши эти параметры внутри кнопки.

2024-09-01 18:43 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_width">match_parent</item>
Атибуты layout_width и layout_height как правило в стиль не выносятся. Концептуально они не относятся к оформлению.

2024-09-01 18:43 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:backgroundTint">@color/vivid_red_color</item>
этот уникальный паарметр вынести в саму кнопку

2024-09-01 18:43 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="36dp"
лучше не ограничивать длину Лейаутов, они лишь область для размещения других объектов. Давай заменим на wrap_content

2024-09-01 18:43 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            style="@style/StyleNavButton2"
Кнопкам тоже напишем wrap_content, чтоб они занимали столько места, сколько им надо для правильной отрисовки контента. Если их длина будет несоответствовать макету, можно воспользоваться параметром padding

2024-09-01 20:55 UTC, ievetrovdev commented
Это было про layout_height параметр. Щас кнопки тоньше снизу чем сверху. Не соответствуют макету. 
layout_width можно и вернуть
<img width="658" alt="Снимок экрана 2024-09-01 в 23 57 18" src="https://github.com/user-attachments/assets/b3b33a5a-9204-43a9-8fc0-65635669e8a0">

2024-09-01 21:20 UTC, M-Vadim-dev commented
> Это было про layout_height параметр. Щас кнопки тоньше снизу чем сверху. Не соответствуют макету. layout_width можно и вернуть <img alt="Снимок экрана 2024-09-01 в 23 57 18" width="658" src="https://private-user-images.githubusercontent.com/153023186/363519167-b3b33a5a-9204-43a9-8fc0-65635669e8a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMjUwNjAsIm5iZiI6MTcyNTIyNDc2MCwicGF0aCI6Ii8xNTMwMjMxODYvMzYzNTE5MTY3LWIzYjMzYTVhLTkyMDQtNDNhOS04ZmMwLTY1NjM1NjY5ZThhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQyMTA2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTIyZDI4MDYyZTNiY2NkZGE2Y2JiNmRiNDk5Y2VhY2Q3MzFmNTgxZTVkYzdhYTFlY2Q1NDU2Y2I1NmZiNzhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ETFB5JztaxCWy0ixm_e7rET9qOAiuRCNpHEDc8v6ssk">

Виноват) подумал про ширину, а не высоту. Почему-то в голове держал высоту как в макете 36dp, что ты писал в телеге: условно говоря высоту кнопок задаем по макету точно, но ширина должна растягиваться.

2024-09-02 18:20 UTC, ievetrovdev commented
> > Это было про layout_height параметр. Щас кнопки тоньше снизу чем сверху. Не соответствуют макету. layout_width можно и вернуть <img alt="Снимок экрана 2024-09-01 в 23 57 18" width="658" src="https://private-user-images.githubusercontent.com/153023186/363519167-b3b33a5a-9204-43a9-8fc0-65635669e8a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMjUwNjAsIm5iZiI6MTcyNTIyNDc2MCwicGF0aCI6Ii8xNTMwMjMxODYvMzYzNTE5MTY3LWIzYjMzYTVhLTkyMDQtNDNhOS04ZmMwLTY1NjM1NjY5ZThhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQyMTA2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTIyZDI4MDYyZTNiY2NkZGE2Y2JiNmRiNDk5Y2VhY2Q3MzFmNTgxZTVkYzdhYTFlY2Q1NDU2Y2I1NmZiNzhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ETFB5JztaxCWy0ixm_e7rET9qOAiuRCNpHEDc8v6ssk">
> 
> Виноват) подумал про ширину, а не высоту. Почему-то в голове держал высоту как в макете 36dp и то что ты писал в телеге: 'условно говоря высоту кнопок задаем по макету точно, но ширина должна растягиваться.'

Вообще в ТЗ прям написано "Высоту кнопок сделать по размеру контента", читай внимательнее и следуй заданию)
Когда ты в xml ставишь фиксированную длину 36dp, то padding перестает работать, поскольку максимальная высота превышена. В твоем случае тебе бы пришлось учитывать, что в Figma указаны нижний и верхний padding по 10dp, тогда итоговая высота будет 56dp. Но таким лучше не заниматься.
Также я выше писал, что ставить у Layout высоту точно не надо, только позволительно у контента внутри

2024-09-02 18:31 UTC, ievetrovdev requested changes

2024-09-02 18:31 UTC, ievetrovdev commented on app/src/main/java/com/example/myapp/MainActivity.kt
> +import com.example.myapp.databinding.ActivityMainBinding
Осталось много пустых импортов. Быстро из файла можно убрать их с помощью ctrl+alt+o

2024-09-02 18:31 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="wrap_content"
Коммент про wrap_content был только для длины. Опять же в задании указано про адаптивность по ширине. Щас ты вручную подогнал размеры, так делать не надо. Мы специально добавили weight, чтоб при match_parent объекты занимали пропорцию

2024-09-02 18:31 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:paddingHorizontal="40dp"
это убрать

2024-09-02 19:00 UTC, ievetrovdev approved these changes
Апрвулю, осталась небольшая проблема, поправь уже в следующей заадче. У тебя на одной кнопке layout_marginEnd="4dp", из-за этого она короче второй на 4dp. Раздели по 2 на каждой

2024-09-02 19:09 UTC, merged