RA-25-update-RecipeState-on-portions-change
M-Vadim-dev/MyApp pull request #22
Opened 2024-10-27 19:44 UTC by M-Vadim-dev

2024-10-28 16:01 UTC, Churickoid requested changes

2024-10-28 16:01 UTC, aGroupoid commented on app/src/main/java/com/example/myapp/ui/recipes/recipe/RecipeViewModel.kt
>          _state.value = _state.value?.copy(isFavorite = isFavorite)
При загрузке рецепта надо еще в стейте обновлять recipe и recipeImage, чтоб они грузились во viewModel.
После этого надо проверить как меняется адаптер после изменения порций

2024-10-28 16:01 UTC, aGroupoid commented on app/src/main/java/com/example/myapp/ui/recipes/recipe/RecipeFragment.kt
> +            binding.rvMethod.adapter = recipeState.recipe?.let { MethodAdapter(it.method) }
Дважды устанавливаются адаптеры

2024-10-28 17:46 UTC, M-Vadim-dev commented on app/src/main/java/com/example/myapp/ui/recipes/recipe/RecipeViewModel.kt
>          _state.value = _state.value?.copy(isFavorite = isFavorite)
Загрузку recipe с STUB не нужно реализовывать STUB.getRecipeById(recipeId) ? Мы потом в TODO сделаем с сети

2024-10-28 17:46 UTC, M-Vadim-dev commented on app/src/main/java/com/example/myapp/ui/recipes/recipe/RecipeFragment.kt
> +            binding.rvMethod.adapter = recipeState.recipe?.let { MethodAdapter(it.method) }
упс, виноват)

2024-10-28 17:57 UTC, Churickoid commented on app/src/main/java/com/example/myapp/ui/recipes/recipe/RecipeViewModel.kt
>          _state.value = _state.value?.copy(isFavorite = isFavorite)
Мы потом реализуем через сеть, пока тестово делаем через STUB.getRecipeById(recipeId). Мы же должны видеть как работает наш ui

2024-10-28 19:55 UTC, Churickoid requested changes
Сейчас на RecipeFragment фото всегда равна null. Попробуй подебажить и найти проблему

2024-10-29 09:48 UTC, Churickoid approved these changes
Всё верно, молодец!

2024-10-29 18:27 UTC, merged