RA-27-add-ViewModel-for-all-screens
M-Vadim-dev/MyApp pull request #24
Opened 2024-11-23 18:35 UTC by M-Vadim-dev

2024-11-24 00:01 UTC, Churickoid requested changes

2024-11-24 00:01 UTC, aGroupoid commented on app/src/main/java/com/example/myapp/ui/categories/CategoriesListFragment.kt
> +        val categoryImageUrl = viewModel.categories.value?.find { it.id == categoryId }?.imageUrl
Обращаться к данным viewModel напрямую - неправильно. Так мы можем попасть в рассинхрон с актуальными данными. Все актуальные данные для фрагмента находятся только в observer. Если логика зависит от этих данных - нужно её перенести под observer, так напрямую ссылаться - не надо. К тому же дважды выполняется поиск по списку, достаточно это делать 1 раз и повторно использовать

2024-11-24 00:01 UTC, aGroupoid commented on app/src/main/java/com/example/myapp/ui/recipes/favorites/FavoritesFragment.kt
>          binding.rvFavorites.adapter = adapter
Сейчас каждый раз при изменении стейта создается новый объект адаптера. Плодить много объектов - не очень хорошая практика, всегда лучше использовать один.
Давай прилинковывать адаптер к ресайклер вью только один раз вне observer. Внутри observer, по аналогии с количеством порций, добавить методе updateDataSet, где будет меняться переменная dataSet. Чтоб ресайклерВью понимал, что ему нужно отрисовать новый список, надо не забыть добавить - notifyDataSetChanged

Также в openRecipeByRecipeId до сих пор используется STUB внутри UI слоя. Это нарушает MVVM, перепиши эту логику через передачу актуальных данных из observer

2024-11-24 00:01 UTC, Churickoid commented on app/src/main/java/com/example/myapp/ui/recipes/recipeList/RecipesListFragment.kt
> +        val adapter = RecipesListAdapter(recipes)
Все те же проблемы, как во фрагменте Избранного

2024-11-30 17:52 UTC, Churickoid approved these changes
Молодец, всё верно!

2024-11-30 19:05 UTC, merged