RA-04-create-first-fragment
M-Vadim-dev/MyApp pull request #3
Opened 2024-09-02 20:34 UTC by M-Vadim-dev

2024-09-03 18:30 UTC, ievetrovdev requested changes

2024-09-03 18:30 UTC, ievetrovdev commented on app/src/main/java/com/example/myapp/MainActivity.kt
>      private lateinit var binding: ActivityMainBinding
lateinit - заманчивая конструкция, но опасная и никак не спасающая от NullPointerException. Вот тут Кирилл Розов наглядно объясняет почему лучше избежать использования lateinit по возможности. https://youtu.be/0nXXUzMyF8c

Лучше стараться продумать подходящее поведение по-умолчанию. В уроке я реализовывал backing property (резервное свойство). Но здесь предлагаю применить более элегантный вариант с помощью делегата lazy, который использует ленивую инициализацию. Это такой механизм, который в лямбде принимает в нашем случае inflate() и возвращает созданный объект, который будет создан при первом обращении к нему.

2024-09-03 18:30 UTC, ievetrovdev commented on app/src/main/java/com/example/myapp/CategoriesListFragment.kt
> +    private val binding get() = _binding!!
!! – оператор-утверждение "это не null" . Как я упоминал ранее – это опасный оператор и не рекомендуется его использовать, тк если в переменную все же придет null – приложение крашнется.

Это отрицательно повлияет на пользовательский опыт и сразу без дебага будет сложно найти причину вылета приложения. Устройств на андройд (и версий андройд) множество, далеко не все работают идеально, как наши собственные или эмулятор. Поэтому, чтобы меньше было проблем в будущем, подкладываем солому заранее. А именно добавляя разные безопасные обработчики.

В уроке я реализовывал backing property (резервное свойство). Но здесь предлагаю применить более элегантный вариант с помощью делегата lazy, который использует ленивую инициализацию. Это такой механизм, который в лямбде принимает в нашем случае inflate() и возвращает созданный объект, который будет создан при первом обращении к нему.

2024-09-03 18:30 UTC, ievetrovdev commented on app/src/main/java/com/example/myapp/MainActivity.kt
> +        fragmentTransaction.add(binding.mainContainer.id, categoryFragment).commit()
Работает, но предлагаю использовать более короткую и свежую форму с применением commit {}. То есть вся магия должна происходить в одной лямбде. Именно для импорта этого метода и метода add() нужно было имплементировать библиотеку fragment-ktx.

Одним из преимуществ этого метода является то, что мы просто указываем тип нового фрагмента, а не передаем экземпляр.
В документации описаны лучшие практики
https://developer.android.com/guide/fragments/create

2024-09-03 18:30 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_marginEnd="2dp"
Все значения не забываем выносить в ресурсы и переиспользовать. Размеры элементов/шрифтов, цвета, строки

2024-09-03 18:30 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_marginStart="2dp"
в ресурсы

2024-09-03 18:30 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
в ресурсы

2024-09-04 17:19 UTC, ievetrovdev requested changes

2024-09-04 17:19 UTC, ievetrovdev commented on app/src/main/java/com/example/myapp/CategoriesListFragment.kt
> +    private val binding: FragmentListCategoriesBinding by lazy(LazyThreadSafetyMode.NONE) {
LazyThreadSafetyMode.NONE надо убрать, всегда код должен быть потокобезопасным

2024-09-04 17:19 UTC, ievetrovdev commented on app/src/main/java/com/example/myapp/MainActivity.kt
> +    private val binding: ActivityMainBinding by lazy(LazyThreadSafetyMode.NONE) {
тут тоже

2024-09-04 17:19 UTC, ievetrovdev commented on app/src/main/java/com/example/myapp/CategoriesListFragment.kt
> +
Поскольку жизненный цикл фрагмента длиннее, чем у view внутри него, рекомендуется очищать binding в методе onDestroyView.
Подробнее можно почитать здесь: https://developer.android.com/topic/libraries/view-binding#fragments

2024-09-04 17:19 UTC, ievetrovdev commented on app/src/main/java/com/example/myapp/MainActivity.kt
> +                add(R.id.mainContainer, CategoriesListFragment())
Ты используешь Java метод add из класса FragmentTransaction.java (посмотри его декларацию). Документация же предлагает импользовать Kotlin extension функцию add() из класса FragmentTransaction.kt.

Именно для импорта метода add нужно было имплементировать библиотеку fragment-ktx. Экстеншн подразумевает принудительное указание типа, а второй параметр с созданием экземпляра фрагмента уже не нужен.
Пример: add<Класс фрагмента>(id)

2024-09-05 16:55 UTC, M-Vadim-dev commented on app/src/main/java/com/example/myapp/CategoriesListFragment.kt
> +
из-за lazy не удается очистить, сменил на другой способ

2024-09-05 18:27 UTC, ievetrovdev approved these changes
Молодец, всё поправил. Да, лучше тогда не использовать lazy для bindnig внутри фрагмента, поскольку очищать binding важнее чем удобная инициализация)
Глянь уже в следующем ПР стили и вынеси все числовые значения в dimens.

2024-09-05 18:29 UTC, merged