RA-35-implement-retrofit-and-repository-pattern
M-Vadim-dev/MyApp pull request #31
Opened 2024-12-07 22:18 UTC by M-Vadim-dev

Немного запутался..  понимаю, что нужно еще поправить после проверки. 
Сложность использования тредов или пулов в репозитории:
1. Трудно управлять доступом к общим ресурсам, что может привести к ошибкам.
2. Найти и исправить ошибки в многопоточном коде сложнее.
3. Нужно следить за потоками, чтобы избежать утечек ресурсов.
4. Неправильное количество потоков может замедлить работу программы.

2024-12-08 20:13 UTC, Churickoid requested changes
Из-за сетевых запросов добавились новые категории. Зайти на супы -> борщ, приложение упадёт. Нужно в адаптере добавить корректную обработку null

2024-12-08 20:13 UTC, aGroupoid commented on app/src/main/java/com/example/myapp/data/recipes.kt
> +            imageUrl = "recipes/burger-cheeseburger.png"
От файла recipes уже стоит отказаться, всё должно работать без него

2024-12-08 20:13 UTC, aGroupoid commented on app/src/main/java/com/example/myapp/data/RecipesRepository.kt
> +        .addConverterFactory(Json.asConverterFactory(CONTENT_TYPE.toMediaType()))
В прошлых уроках мы учились добавлять Interceptor, Ретрофит поддерживает все функции okHttp, необходимо его прописать, чтоб в logcat логгировался весь твой трафик

2024-12-08 20:13 UTC, aGroupoid commented on app/src/main/java/com/example/myapp/data/RecipesRepository.kt
> +        return try {
Хвалю за то что решил вынести в отдельный служебный метод. Хороший тон если все приватные функции находятся внизу класса, публичные - вверху. Нужно перенести

2024-12-08 20:13 UTC, Churickoid commented on app/src/main/java/com/example/myapp/data/RecipesRepository.kt
> +        val INSTANCE_RECIPES_REPOSITORY: RecipesRepository by lazy { RecipesRepository() }
Досточно просто назвать INSTANCE, ведь получить доступ к нему можно лишь через обращение к RecipesRepository.INCTANCE. Дополнительной инфы в нейминге не надо

2024-12-08 20:13 UTC, Churickoid commented on app/src/main/java/com/example/myapp/data/RecipesRepository.kt
> +        return recipe?.imageUrl.toString()
Здесь делается повторный интернет запрос, хотя getRecipeById делается во viewModel выше. Неоптимизровано получается, лучше от этого метода полностью отказаться и работать с информацией локально

2024-12-08 20:13 UTC, Churickoid commented on app/src/main/java/com/example/myapp/ui/categories/CategoriesListFragment.kt
>              categoriesAdapter.setOnItemClickListener(object :
Этот код нужно вынести из observer, каждый раз подключать при изменении стейта новый листенер - не хорошо

2024-12-08 20:13 UTC, Churickoid commented on app/src/main/java/com/example/myapp/utils/ThreadPoolProvider.kt
> +    fun getThreadPool(): ExecutorService = threadPool
Делать отдельный геттер - более джавовский подход. В котлин рекомендуется обращаться к переменным напрямую, без создания этой функции

2024-12-08 20:13 UTC, Churickoid commented on app/src/main/java/com/example/myapp/ui/recipes/favorites/FavoritesViewModel.kt
> +                } else _favoriteRecipes.postValue(favoritesList.toList())
Это условие лишнее, если пустой список - и так положиться пустой список. 
Также сейчас на экране избранного не показывается уведомление об ошибки сети - выводится как будто список пустой. Нужно корректно обрабатывать этот стейт и доработать логику

2024-12-09 16:44 UTC, M-Vadim-dev commented on app/src/main/java/com/example/myapp/ui/recipes/favorites/FavoritesViewModel.kt
> +                } else _favoriteRecipes.postValue(favoritesList.toList())
По избранным рецептам затуп чето), это мне надо в стейт внести состояния отслеживания ошибки?

2024-12-10 12:05 UTC, Churickoid commented on app/src/main/java/com/example/myapp/ui/recipes/favorites/FavoritesViewModel.kt
> +                } else _favoriteRecipes.postValue(favoritesList.toList())
Нужно разделить состояние пустого списка и null-списка. Когда приходит null - ошибка и показываем тост, если пустой - текст с пустым избранным

2024-12-10 13:22 UTC, Churickoid approved these changes
По заданию всё верно, молодец! Поправь в следующем ПР 1 коммент

2024-12-10 17:51 UTC, merged