RA-36-load-images-with-glide
M-Vadim-dev/MyApp pull request #32
Opened 2024-12-10 22:49 UTC by M-Vadim-dev

2024-12-11 07:45 UTC, M-Vadim-dev commented
где-то неправильно взаимодействую с API, прилетает ошибка 500

2024-12-11 14:18 UTC, Churickoid requested changes
На экране категорий не показывается тост при выключенном интернете, нужно поправить

2024-12-11 14:18 UTC, Churickoid commented on app/src/main/java/com/example/myapp/ui/recipes/recipe/RecipeViewModel.kt
> +    val recipeImageUrl: String? = null,
Давай от этого параметра уже избавимся, он содержится внутри recipe и так

2024-12-11 14:18 UTC, Churickoid commented on app/src/main/java/com/example/myapp/ui/recipes/favorites/FavoritesFragment.kt
> +                    showEmptyState(true)
Лучше не показывать надпись "Вы не добавили ни одного рецепта" при сетевой ошибки, это только запутает пользователя. Только тост

2024-12-11 14:19 UTC, Churickoid commented
По поводу 500, с твоей стороны всё ок, скорее всего сервер не успевал обработать все твои запросы. Это проблема бэка

2024-12-11 14:54 UTC, M-Vadim-dev commented
> По поводу 500, с твоей стороны всё ок, скорее всего сервер не успевал обработать все твои запросы. Это проблема бэка

Так меня это сбивает постоянно) Через дебаг вижу, что у меня постоянно Null прилетает с бэка 500 и Тост всегда показывает)

2024-12-12 08:49 UTC, Churickoid approved these changes
Про этот тест-кейс понял. То что ты описал, это уже проблема с твоей стороны. Если в преференсах ничего не лежит - не нужно идти в интернет, список и так пустой. Он тебе возвращать 500 потому что ты отправляешь на бэк пустую строку, а он не знает что тебе вернуть. Поправь в следующем пр

2024-12-12 09:20 UTC, merged