RA-39-add-caching-for-categories
M-Vadim-dev/MyApp pull request #35
Opened 2024-12-15 12:18 UTC by M-Vadim-dev

2024-12-15 17:47 UTC, Churickoid requested changes
По прошлым ПР надо доделать: При ошибки вызова должен выводиться toast, что произошла ошибка. Для этого в state нужно отправлять определенные данные и обрабатывать их на урвоне фрагмента вызовом тоста

2024-12-15 17:47 UTC, Churickoid commented on app/src/main/java/com/example/myapp/data/RecipesRepository.kt
> +        return@withContext remoteCategories
У тебя есть отдельные ручки insertCategoriesFromCache и getCategoriesFromCache. В этом блоке дублируется логика этих ручек. Вообще функции репозитория должны делать не много, вся это логика должна быть на уровне viewModel, особенно если она не дублируется в других классах. Такие большие блоки кода можно вынести в репозиторий в случае частого их использования в таком виде

2024-12-15 17:47 UTC, Churickoid commented on app/src/main/java/com/example/myapp/ui/recipes/recipeList/RecipesListFragment.kt
> +        RecipesListViewModelFactory(requireActivity().application)
В таких случаях лучше не делать кастомную фабрику. Если нужен Application во viewModel - существует класс AndroidViewModel, надо наследоваться от него

2024-12-15 21:28 UTC, M-Vadim-dev commented on app/src/main/java/com/example/myapp/ui/recipes/recipeList/RecipesListFragment.kt
> +        RecipesListViewModelFactory(requireActivity().application)
понял, её тогда лучше вообще не использовать)

2024-12-16 09:28 UTC, Churickoid requested changes
На экране рецептов и списка рецептов всё еще нету логики тоста

2024-12-16 09:28 UTC, Churickoid commented on app/src/main/java/com/example/myapp/ui/categories/CategoriesListViewModel.kt
> +                _categories.value = CategoriesListState(dataSet = categories)
При успешном запросе надо обнулять errorMessage, иначе после первого неудачного запроса - всегда будет отображаться toast

2024-12-16 09:28 UTC, Churickoid commented on app/src/main/java/com/example/myapp/ui/categories/CategoriesListViewModel.kt
> +                    CategoriesListState(errorMessage = "Ошибка получения данных")
Текущий подход не поддерживает локализацию на разных девайсах. Всегда будет захардкоженная надпись на русском. Лучше всего создать enum class с разными типами ошибок, а в зависимости от типа ошибки показывать конкретный строковой ресурс

2024-12-17 10:31 UTC, Churickoid approved these changes
Всё верно, молодец!

2024-12-17 18:20 UTC, merged