RA-40-add-caching-for-recipes-list
M-Vadim-dev/MyApp pull request #36
Opened 2024-12-17 21:34 UTC by M-Vadim-dev

2024-12-18 12:50 UTC, Churickoid requested changes

2024-12-18 12:50 UTC, Churickoid commented on app/src/main/java/com/example/myapp/ui/recipes/recipe/RecipeViewModel.kt
> +                val remoteRecipe = recipesRepository.getRecipeById(recipeId)
Давай еще отредактируем RecipeFragment и её вью модель. Как и с категориями, через safeArgs передавать рецепт. Избавимся от лишнего хождения в интернет, за одно и проверим все ли данные коректно приходят из аргументов

2024-12-18 19:47 UTC, M-Vadim-dev commented on app/src/main/java/com/example/myapp/ui/recipes/recipe/RecipeViewModel.kt
> +                val remoteRecipe = recipesRepository.getRecipeById(recipeId)
Хотел еще спросить, нужно ли оборачивать сетевые запросы mutex.withLock ?

2024-12-18 19:51 UTC, M-Vadim-dev commented on app/src/main/java/com/example/myapp/ui/recipes/recipe/RecipeViewModel.kt
> +                val remoteRecipe = recipesRepository.getRecipeById(recipeId)
Вопрос, нужно ли оборачивать сетевые вызовы в mutex.withLock или когда его обычно использовать?

2024-12-19 09:08 UTC, Churickoid approved these changes
Молодец, всё верно!

2024-12-19 09:08 UTC, aGroupoid commented on app/src/main/java/com/example/myapp/ui/recipes/recipe/RecipeViewModel.kt
> +        _state.value = RecipeState(recipe = recipe, isFavorite = isFavorite)
Нужно присваивать через .copy, иначе сотруться portionsCount и errorType, если они будут установлены

2024-12-19 18:16 UTC, merged